name: 'Setup Environment'
description: 'Prepares the CI environment for other workflows'
inputs:
  node-version:
    description: 'Node.js version to setup'
    required: true
  
  install-deps:
    description: 'Whether to install dependencies'
    required: false
    default: true

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "npm"

    - name: Install dependencies
      if: ${{ inputs.install-deps }}
      run: npm ci
      shell: bash
      