name: Publish

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Version or Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup environment
        uses: ./.github/actions/setup-ci-env
        with:
          install-deps: true
          node-version: lts/*

      - name: Build artifacts
        run: pnpm run build

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@a45c4d594aa4e2c509dc14a9f2b3b67ba3780d0d # v1.9.0
        with:
          version: pnpm run changeset -- version
          publish: pnpm run changeset -- publish
          commit: "ci: release package"
          title: "[CI] Release Package"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}

      - name: Generate Slack Announcement
        id: announcement
        if: steps.changesets.outputs.published == 'true'
        run: |
          # From Node v22.18.0, the node command is able to run .ts files directly (if it only needs type stripping).
          # As of August 2025, Node v22.18.0 is already LTS (the version used by this workflow).
          SLACK_WEBHOOK_PAYLOAD="$(node .github/scripts/announce.ts '${{ steps.changesets.outputs.publishedPackages }}')"
          echo "SLACK_WEBHOOK_PAYLOAD=$SLACK_WEBHOOK_PAYLOAD" >> "$GITHUB_OUTPUT"
      
      - name: Notify on Slack
        uses: slackapi/slack-github-action@dcb1066f776dd043e64d0e8ba94ca15cc7e1875d # v4.0.0
        if: steps.changesets.outputs.published == 'true'
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: ${{ steps.announcement.outputs.SLACK_WEBHOOK_PAYLOAD }}
